server {
  listen 80;
  server_name _;

  # If we return 418 from location /, route internally to @prerender
  error_page 418 = @prerender;

  location / {
    set $prerender 0;

    if ($http_user_agent ~* "googlebot|bingbot|yandex|baiduspider|facebookexternalhit|twitterbot|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator|whatsapp|applebot|duckduckbot") {
      set $prerender 1;
    }

    if ($args ~* "_escaped_fragment_") {
      set $prerender 1;
    }

    if ($http_user_agent ~* "Prerender") {
      set $prerender 0;
    }

    if ($uri ~* "\.(js|css|xml|less|png|jpg|jpeg|gif|pdf|doc|txt|ico|rss|zip|mp3|rar|exe|wmv|avi|ppt|mpg|mpeg|tif|wav|mov|psd|ai|xls|mp4|m4a|swf|dat|dmg|iso|flv|m4v|torrent|woff|woff2|ttf|eot|svg|map)$") {
      set $prerender 0;
    }

    if ($prerender = 1) {
      return 418;
    }

    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location @prerender {
    rewrite .* /$scheme://$host$request_uri? break;
    proxy_pass http://service.prerender.io;
    proxy_set_header X-Prerender-Token E1Bwll1bPvtFUxUATZLn;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
  }
}